name: main

on:
  push:
    branches: ['*']
  workflow_dispatch:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Build jar
        run: gradle shadowJar

      - name: Rename jar
        run: mv app/build/libs/app-all.jar groovy-conf-updater-r${{ github.run_number }}.jar

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.run_number }}
          tag_name: r${{ github.run_number }}
          fail_on_unmatched_files: true
          files: groovy-conf-updater-r${{ github.run_number }}.jar
